<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Employee;

/**
 * CooptationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CooptationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByUser(Employee $employee)
    {
        return $this->createQueryBuilder('c')
            ->where('c.employee = :employee')
            ->setParameter('employee', $employee)
            ->getQuery()->getResult();
    }
}
