<?php

namespace AppBundle\Repository;

/**
 * EmailTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
