<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Employee;

/**
 * EmployeeNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeNotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function countUnseenByEmployeeId(Employee $employee){
        return $this->createQueryBuilder('e')
            ->select('COUNT(e)')
            ->where('e.employeeId = :employeeId')
            ->andWhere('e.seen = false')
            ->andWhere('e.archived = false')
            ->setParameter(employeeId, $employee->getId())
            ->getQuery()
            ->getSingleScalarResult();
    }
}
