<?php

namespace AppBundle\Repository;

/**
 * EmployeeFormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeFormationRepository extends \Doctrine\ORM\EntityRepository
{
}
