<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Employee;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByEmployee(Employee $employee)
    {
        return $this->createQueryBuilder('f')
            ->where('f.employee = :employee')
            ->setParameter('employee', $employee)
            ->getQuery()->getResult();
    }
    public function findEmployeeLastFormation(Employee $employee)
    {
        $qb =$this->createQueryBuilder('e');

        $qb
            ->where('e.employee = :employeeId')
            ->orderBy('e.startDate','DESC')
            ->setMaxResults(1)
            ->setParameter('employeeId', $employee->getId());

        ;

        return $qb
            ->getQuery()
            ->getOneOrNullResult();
        ;
    }
    public function findEmployeeAllFormations(Employee $employee)
    {
        $qb = $this->createQueryBuilder('e');
        $qb
            ->where('e.employee = :employeeId')
            ->setParameter('employeeId',  $employee->getId())
            ->orderBy('e.startDate','DESC')

        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

}
