<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Employee;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends AbstractRepository
{

    public function findAllQuery(
        $orderBy = null,
        $direction = 'desc'
    )
    {
        $qb = $this->createQueryBuilder('f');

        if ($orderBy)
            $qb->orderBy('f.'.$orderBy, $direction);

        return $qb->getQuery();
    }


    public function findAllByEmployeeQuery(
        $orderBy = null,
        $direction = 'desc',
        Employee $employee = null
    )
    {


        $qb = $this->createQueryBuilder('e');

        if ($orderBy)
            $qb->orderBy('e.'.$orderBy, $direction);
        if (null !== $employee)
            $qb->where('e.employee = :employee')
                ->setParameter('employee', $employee);

        return $qb->getQuery();
    }


    public function findAllByEmployee(Employee $employee)
    {
        return $this->createQueryBuilder('f')
            ->where('f.employee = :employee')
            ->setParameter('employee', $employee)
            ->getQuery()->getResult();
    }

    public function findEmployeeLastFormation(Employee $employee)
    {
        $qb =$this->createQueryBuilder('e');

        $qb
            ->where('e.employee = :employeeId')
            ->orderBy('e.startDate','DESC')
            ->setMaxResults(1)
            ->setParameter('employeeId', $employee->getId());

        ;

        return $qb
            ->getQuery()
            ->getOneOrNullResult();
        ;
    }
    public function findEmployeeAllFormations(Employee $employee)
    {
        $qb = $this->createQueryBuilder('e');
        $qb
            ->where('e.employee = :employeeId')
            ->setParameter('employeeId',  $employee->getId())
            ->orderBy('e.startDate','DESC')

        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

}
