<?php

namespace AppBundle\Repository;

/**
 * NotificationReferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationReferenceRepository extends \Doctrine\ORM\EntityRepository
{
}
