<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Employee;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{


}
