<?php

namespace AppBundle\Repository;

use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * NotificationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationTypeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByLabel($notificationType)
    {
        $qb = $this->createQueryBuilder('n')
            ->where('n.label = :notificationType')
            ->setParameter('notificationType', $notificationType);

        try
        {
            return $qb->getQuery()
                ->getSingleResult();
        }catch(NoResultException $nre){
        }catch (NonUniqueResultException $nure){
        }
    }
}
