<?php

namespace AppBundle\Repository;

/**
 * ReligiousPaidVacationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReligiousPaidVacationRepository extends \Doctrine\ORM\EntityRepository
{
}
