app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix:

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

app_api:
    resource: "@AppBundle/Controller/Api"
    type:     annotation
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

