# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']
    
    app.vacation.manager:
        class: 'AppBundle\Manager\VacationManager'
        public: true
        arguments: ['@doctrine.orm.entity_manager','@app.notification.manager','@app.email.manager']

    app.notification.manager:
        class: 'AppBundle\Manager\NotificationManager'
        public: true


    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'
    
    app.xls.manager:
        class: 'AppBundle\File\Manager\ExcelManager'
        public: true

    app.cooptation.manager:
        class: 'AppBundle\Manager\CooptationManager'
        public: true

    app.employee.manager:
        class: 'AppBundle\Manager\EmployeeManager'
        public: true

    app.employee_formation.manager:
        class: 'AppBundle\Manager\EmployeeFormationManager'
        public: true
        arguments: ['@doctrine.orm.entity_manager']

    app.email.manager:
        class: 'AppBundle\Manager\EmailManager'
        public: true

    app.pdf.manager:
        class: 'AppBundle\File\Manager\PDFManager'
        public: true

    app.docs.manager:
        class: 'AppBundle\Manager\docsManager'
        public: true

    employee.subscriber:
        class: 'AppBundle\EventListener\EmployeeSubscriber'
        public: true
        arguments : ['@security.token_storage','@security.authorization_checker','@router']
        tags:
            - { name : kernel.event_subscriber }

    vacation_date_validator:
        class: 'AppBundle\Validator\Constraints\VacationPeriodeValidator'
        arguments: ['@doctrine.orm.entity_manager','@app.vacation.manager','@security.token_storage']
        tags:
            -
                name: 'validator.constraint_validator'
                alias: 'vacation_date_validator'
