AppBundle\Entity\EmployeeNotification:
    exclusion_policy: all
    xml_root_name: employee_notification
    properties:
        id:
            expose: true
            groups: [list]
        seen:
            expose: true
            groups: [list]
        notification:
            expose: true
            groups: [list]
