Knp\Component\Pager\Pagination\AbstractPagination:
    exclusion_policy: ALL
    xml_root_name: abstract_pagination
    properties:
        items:
            expose: true
            access_type: public_method
            accessor:
                getter: getItems
            type: array
            serialized_name:
                payload
        currentPageNumber:
            expose: true
            serialized_name:
                page
        numItemsPerPage:
            expose: true
            serialized_name:
                items
        totalCount:
            expose: true
            serialized_name:
                totalItems
        pageRange:
            expose: true
            serialized_name:
                pageRange

